### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by pythonmobile** [bdytx5/mistral7B_finetune#1]
I was trying your repo and got into this runtime error. Any ideas on how to fix this?

[E ProcessGroupNCCL.cpp:916] [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=131072000, NumelOut=131072000, Timeout(ms)=1800000) ran for 1800340 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] NCCL watchdog thread terminated with exception: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=131072000, NumelOut=131072000, Timeout(ms)=1800000) ran for 1800340 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:489] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:495] To avoid data inconsistency, we are taking the entire process down.
[E ProcessGroupNCCL.cpp:916] [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=131072000, NumelOut=131072000, Timeout(ms)=1800000) ran for 1800341 milliseconds before timing out.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] NCCL watchdog thread terminated with exception: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=BROADCAST, NumelIn=131072000, NumelOut=131072000, Timeout(ms)=1800000) ran for 1800341 milliseconds before timing out.
[2023-12-23 11:17:48,719] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2251
[2023-12-23 11:17:48,719] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 2252
[2023-12-23 11:18:18,750] [ERROR] [launch.py:321:sigkill_handler] ['/usr/bin/python3', '-u', 'train.py', '--local_rank=1'] exits with return code = -6

**Comment by bdytx5** [comment]
looks like cpu OOM https://github.com/microsoft/DeepSpeed/issues/2852 -- also see the bottom of the readme
